name: PR Lint Format

on:
  pull_request:
    paths:
    - 'drivers/**'
    - 'lib/arm_atsam/**'
    - 'lib/lib8tion/**'
    - 'lib/python/**'
    - 'platforms/**'
    - 'quantum/**'
    - 'tests/**'
    - 'tmk_core/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: trilom/file-changes-action@v1.2.4
      id: file_changes
      with:
        output: ' '
        fileOutput: ' '

    - name: Run qmk format-c and qmk format-python
      shell: 'bash {0}'
      run: |
        qmk format-c --core-only -n $(< ~/files.txt)
        format_c_exit=$?
        qmk format-python -n
        format_python_exit=$?

        exit $((format_c_exit + format_python_exit))
